### ISSUE TITLE
How to see a parse tree / AST for a card?

### ISSUE THREAD

**Issue by flyingmutant** [Zannick/demystify#2]
Sorry if I missed something obvious, but what should I type after `python3 demistify.py load -i` to see a parse tree or AST for a given card?

**Comment by Zannick** [comment]
None of the parsing happens automatically. You have to grab a set of cards and pass them to one of the parse methods in demystify.

```python
>>> c = card.get_card('Akroma')
>>> c
<card.Card instance {'rules': 'flying, first strike, vigilance, trample, haste, protection from black and from red', 'multicard': None, 'shortname': 'Akroma', 'multitype': None, 'typeline': 'legendary creature — angel', 'pt': '6/6', 'sets': ['LGN', 'TSP'], 'color': None, 'name': 'Akroma, Angel of Wrath', 'cost': '5WWW'}>
>>> parse_all([c])
>>> parse_keyword_lines([c])
>>> c.parsed_keywords
['(KEYWORDS flying FIRST_STRIKE vigilance trample haste (protection (PROPERTIES black) (PROPERTIES red)))']
>>> c.parsed_cost
<antlr3.tree.CommonTree instance (COST (MANA W W W 5))>
>>> c.parsed_typeline
<antlr3.tree.CommonTree instance (TYPELINE (SUPERTYPES legendary) (TYPES creature) (SUBTYPES angel))>
```

Not everything is parseable yet, either. parse_all only does cost and typeline, parse_ability_costs grabs the ability costs and parses them, and parse_triggers will only parse the triggers. My usual debugging strategy is to run `parse_triggers(get_cards())` and then check `LOG` for errors.
