### ISSUE TITLE
Preview output of a parsed card?

### ISSUE THREAD

**Issue by PAK90** [Zannick/demystify#3]
Not really an issue per se; I was looking through the docs and was hoping to find an example of a parsed card, especially the rules text. I'm looking into building a parser for rules text and found your project, I just can't tell if it'll produce the sort of output I'm looking for. For example, what does the parsed version of Liliana of the Veil look like?

**Comment by Zannick** [comment]
Hey, thanks for the feedback. I added a section to the README with some examples. Unfortunately, the parser's nowhere near completion, so about all I have for Liliana is her mana cost, types, and ability costs, which look like this, respectively:

```
(COST (MANA B B 1))
(TYPELINE (TYPES planeswalker) (SUBTYPES liliana))
['(COST (LOYALTY PLUS 1))',
 '(COST (LOYALTY MINUS 2))',
 '(COST (LOYALTY MINUS 6))']
```

In general, I'm creating abstract syntax trees for the abilities, but it's not quite there yet on many large parts, such as effects, trigger conditions, and some unique ability costs. You can see better examples of some currently parseable phrases in tests/.
